### ISSUE TITLE
hardcoded repo name when opening a document

### ISSUE THREAD

**Issue by nbossard** [ALegendsTale/omnisearch-companion#1]
Hello,
Thanks for your plugin.

Think I found an issue. When clicking on the result of a search for opening corresponding document I get an error.

>Unable to find a vault for the URL obsidian://open?vault=ObsidianVault&file=Permanent/Maison%20de%20Lancieux/Maison%20Lancieux.md

It seems the vault name "ObsidianVault"is hardcoded : In file NoteItem.ts line 40 we can see :             
```javascript
browser.tabs.update({ url: `obsidian://open?vault=ObsidianVault&file=${note.path}` }); 
```
Could it be customisable in plugin settings?

**Comment by nbossard** [comment]
Even better we should use vault name provided in server response. e.g. : 
```jsonc
﻿[
  {
    "score": 130.0691119456879,
    "vault": "obsperso", // <=========================== use this name =====================
    "path": "Permanent/Informatique/Figma.md",
    "basename": "Figma",
    "foundWords": ["figma"],
    "matches": [
      { "match": "Figma", "offset": 131 },
      { "match": "figma", "offset": 161 },
      { "match": "figma", "offset": 827 },
      { "match": "figma", "offset": 888 }
    ],
    "excerpt": "# Figma<br>Adresse:: &lt;https://www.figma.com/&gt;"
  },
  {
    "score": 114.18705150313593,
    "vault": "obsperso",
    "path": "contacts/pro/Arthur de FIGMA.md",
    "basename": "Arthur de FIGMA",
    "foundWords": ["figma"],
    "matches": [
      { "match": "FIGMA", "offset": 12 },
      { "match": "FIGMA", "offset": 37 },
      { "match": "Figma", "offset": 114 }
    ],
    "excerpt": "..."
  }
]
```

**Comment by ALegendsTale** [comment]
Hello,
That's a really silly oversight on my part, thanks a lot for letting me know!
I'll have a fix for it published today.

**Comment by ALegendsTale** [comment]
Thank you so much for letting me know about this! I've had a few users mention about not being able to open notes but completely overlooked this.

The patched version has been uploaded to the Chrome & Firefox stores and await the review process. The same extension packages are also available on the [1.4.3 release page](https://github.com/ALegendsTale/omnisearch-companion/releases/tag/1.4.3). The `.crx` works with Chrome and the `.xpi` works with Firefox.

**Comment by nbossard** [comment]
Cool you fixed it, will test it ASAP and confirm you it works.
Best regards, Nicolas.

**Comment by nbossard** [comment]
Ok tested it works, great job 👏
